import {
  collection,
  addDoc,
  updateDoc,
  deleteDoc,
  doc,
  serverTimestamp,
  type WithFieldValue
} from 'firebase/firestore';
import { db } from '@/lib/firebase/config';
import type { Product } from '@/types';

// The input type should not include fields that are auto-generated by Firestore.
type ProductInput = Omit<Product, 'id' | 'createdAt'>;
type ProductUpdateInput = Partial<ProductInput>;

const productsCollection = collection(db, 'products');

export const addProduct = (productData: ProductInput) => {
  const dataWithTimestamp: WithFieldValue<ProductInput> = {
    ...productData,
    createdAt: serverTimestamp(),
  };
  return addDoc(productsCollection, dataWithTimestamp);
};

export const updateProduct = (id: string, productData: ProductUpdateInput) => {
  const productDoc = doc(db, 'products', id);
  return updateDoc(productDoc, productData);
};

export const deleteProduct = (id: string) => {
  const productDoc = doc(db, 'products', id);
  return deleteDoc(productDoc);
};
